project:
  type: website

website:
  sidebar:
    style: "floating"
    contents:
      - href: index.qmd
        text: HOME
      - section: "THEORY"
        contents:
        - analyses/explore-emg.qmd
        - analyses/met-precision.qmd
        - analyses/janowski.qmd
        - analyses/many-takepoints.qmd
        - analyses/bgmoves-analysis.qmd
      - section: "PRAXIS"
        contents:
        - analyses/milestones-2023.qmd
        - analyses/mistakes.qmd
        - analyses/opening-mistakes.qmd
        - analyses/middle-game-cubes.qmd

    search: true
      
format:
  html:
    theme: litera
    css: styles.css
    toc: true
email-obfuscation: javascript
    
execute:
  freeze: auto