project:
  type: website

website:
  title: "BG analyses"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - analyses/explore-emg.qmd
      - analyses/met-precision.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    
execute:
  freeze: auto



