project:
  type: website

website:
  title: "bganalyses"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - analyses/explore-emg.qmd
      - analyses/met-precision.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



