project:
  type: website

website:
  sidebar:
    style: "floating"
    contents:
      - href: index.qmd
        text: Home
      - analyses/explore-emg.qmd
      - analyses/met-precision.qmd
      - analyses/janowski.qmd
      - analyses/milestones-2023.qmd
      - analyses/many-takepoints.qmd
    search: true
      
format:
  html:
    theme: litera
    css: styles.css
    toc: true
email-obfuscation: javascript
    
execute:
  freeze: auto