<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.551">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lasse Hjorth Madsen">
<meta name="dcterms.date" content="2025-04-18">

<title>The five point match</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../analyses/milestones-2023.html">PRAXIS</a></li><li class="breadcrumb-item"><a href="../analyses/5-point-match.html">The five point match</a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">HOME</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">THEORY</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analyses/explore-emg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explore EMG Normalization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analyses/met-precision.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Match Equity Precision</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analyses/janowski.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Janowski Formulars</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analyses/many-takepoints.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exploring take points</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analyses/bgmoves-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mistake, errors and statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analyses/pr-confidence-intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Confidence intervals for PR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analyses/big-cubes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Big Cubes</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">PRAXIS</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analyses/milestones-2023.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Milestones III, 2023</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analyses/player-mistakes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mistakes were made</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analyses/opening-mistakes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Opening checker play errors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analyses/middle-game-cubes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Middle game cube benchmark</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analyses/hit-or-point.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hit or point decisions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analyses/5-point-match.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">The five point match</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#why-this" id="toc-why-this" class="nav-link active" data-scroll-target="#why-this">Why this?</a></li>
  <li><a href="#positions-types" id="toc-positions-types" class="nav-link" data-scroll-target="#positions-types">Positions types</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a>
  <ul>
  <li><a href="#match-equity-table" id="toc-match-equity-table" class="nav-link" data-scroll-target="#match-equity-table">Match equity table</a></li>
  <li><a href="#take-point-plots" id="toc-take-point-plots" class="nav-link" data-scroll-target="#take-point-plots">Take point plots</a></li>
  </ul></li>
  <li><a href="#pre-crawford" id="toc-pre-crawford" class="nav-link" data-scroll-target="#pre-crawford">Pre-crawford</a>
  <ul>
  <li><a href="#away-scores" id="toc-away-scores" class="nav-link" data-scroll-target="#away-scores">5-away scores</a>
  <ul class="collapse">
  <li><a href="#away-5-away" id="toc-away-5-away" class="nav-link" data-scroll-target="#away-5-away">5-away, 5-away</a></li>
  <li><a href="#away-5-away-1" id="toc-away-5-away-1" class="nav-link" data-scroll-target="#away-5-away-1">4-away, 5-away</a></li>
  <li><a href="#away-5-away-2" id="toc-away-5-away-2" class="nav-link" data-scroll-target="#away-5-away-2">3-away, 5-away</a></li>
  <li><a href="#away-5-away-3" id="toc-away-5-away-3" class="nav-link" data-scroll-target="#away-5-away-3">2-away, 5-away</a></li>
  <li><a href="#away-4-away" id="toc-away-4-away" class="nav-link" data-scroll-target="#away-4-away">5-away, 4-away</a></li>
  <li><a href="#away-3-away" id="toc-away-3-away" class="nav-link" data-scroll-target="#away-3-away">5-away, 3-away</a></li>
  <li><a href="#away-2-away" id="toc-away-2-away" class="nav-link" data-scroll-target="#away-2-away">5-away, 2-away</a></li>
  </ul></li>
  <li><a href="#away-scores-1" id="toc-away-scores-1" class="nav-link" data-scroll-target="#away-scores-1">4-away scores</a>
  <ul class="collapse">
  <li><a href="#away-4-away-1" id="toc-away-4-away-1" class="nav-link" data-scroll-target="#away-4-away-1">4-away, 4-away</a></li>
  <li><a href="#away-4-away-2" id="toc-away-4-away-2" class="nav-link" data-scroll-target="#away-4-away-2">3-away, 4-away</a></li>
  <li><a href="#away-4-away-3" id="toc-away-4-away-3" class="nav-link" data-scroll-target="#away-4-away-3">2-away, 4-away</a></li>
  <li><a href="#away-3-away-1" id="toc-away-3-away-1" class="nav-link" data-scroll-target="#away-3-away-1">4-away, 3-away</a></li>
  <li><a href="#away-2-away-1" id="toc-away-2-away-1" class="nav-link" data-scroll-target="#away-2-away-1">4-away, 2-away</a></li>
  </ul></li>
  <li><a href="#away-scores-2" id="toc-away-scores-2" class="nav-link" data-scroll-target="#away-scores-2">3-away scores</a>
  <ul class="collapse">
  <li><a href="#away-3-away-2" id="toc-away-3-away-2" class="nav-link" data-scroll-target="#away-3-away-2">3-away, 3-away</a></li>
  <li><a href="#away-3-away-3" id="toc-away-3-away-3" class="nav-link" data-scroll-target="#away-3-away-3">2-away, 3-away</a></li>
  <li><a href="#away-2-away-2" id="toc-away-2-away-2" class="nav-link" data-scroll-target="#away-2-away-2">3-away, 2-away</a></li>
  </ul></li>
  <li><a href="#the-funny-two-point-match" id="toc-the-funny-two-point-match" class="nav-link" data-scroll-target="#the-funny-two-point-match">The funny two-point match</a></li>
  </ul></li>
  <li><a href="#post-crawford" id="toc-post-crawford" class="nav-link" data-scroll-target="#post-crawford">Post-crawford</a>
  <ul>
  <li><a href="#away-even-away" id="toc-away-even-away" class="nav-link" data-scroll-target="#away-even-away">1-away, even-away</a></li>
  <li><a href="#even-away-1-away" id="toc-even-away-1-away" class="nav-link" data-scroll-target="#even-away-1-away">Even-away, 1-away</a></li>
  <li><a href="#away-odd-away" id="toc-away-odd-away" class="nav-link" data-scroll-target="#away-odd-away">1-away, odd-away</a></li>
  <li><a href="#odd-away-1-away" id="toc-odd-away-1-away" class="nav-link" data-scroll-target="#odd-away-1-away">Odd-away, 1-away</a></li>
  </ul></li>
  <li><a href="#recubes" id="toc-recubes" class="nav-link" data-scroll-target="#recubes">Recubes</a>
  <ul>
  <li><a href="#away-5-away-4" id="toc-away-5-away-4" class="nav-link" data-scroll-target="#away-5-away-4">5-away, 5-away</a></li>
  <li><a href="#away-5-away-5" id="toc-away-5-away-5" class="nav-link" data-scroll-target="#away-5-away-5">4-away, 5-away</a></li>
  <li><a href="#away-5-away-6" id="toc-away-5-away-6" class="nav-link" data-scroll-target="#away-5-away-6">3-away, 5-away</a></li>
  <li><a href="#away-4-away-4" id="toc-away-4-away-4" class="nav-link" data-scroll-target="#away-4-away-4">5-away, 4-away</a></li>
  <li><a href="#away-3-away-4" id="toc-away-3-away-4" class="nav-link" data-scroll-target="#away-3-away-4">5-away, 3-away</a></li>
  </ul></li>
  <li><a href="#the-rare-8-cube" id="toc-the-rare-8-cube" class="nav-link" data-scroll-target="#the-rare-8-cube">The rare 8-cube</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../analyses/milestones-2023.html">PRAXIS</a></li><li class="breadcrumb-item"><a href="../analyses/5-point-match.html">The five point match</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">The five point match</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Lasse Hjorth Madsen </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 18, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="why-this" class="level2">
<h2 class="anchored" data-anchor-id="why-this">Why this?</h2>
<p>This is walk-through of all scores in a five point match. We examine how take points and cube dynamic varies across scores, with sample positions to illustrate differences.</p>
<p>The goal is to try to better understand the <em>match scores</em>, not so much any particular position.</p>
</section>
<section id="positions-types" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="positions-types">Positions types</h2>
<p>To show differences due to gammons, we consider five different types of positions:</p>
<ul>
<li>Last roll: Truly last roll, with not even automatic recubes</li>
<li>No gammons: Zero gammon but possibly some cube leverage</li>
<li>A little gammon: Typically early middle games with anchors</li>
<li>Some gammons: No-anchor middle games</li>
<li>Many gammons: Blitzes and back games</li>
</ul>
<p>What do the different gammon situations look like? Below are the examples we will use for examination here, along with money game rollouts.</p>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/pos1-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Player Winning Chances:   75,00% (G:0,00% B:0,00%)
Opponent Winning Chances: 25,00% (G:0,00% B:0,00%)
Cubeless Equities: No Double=+0,500, Double=+1,000
Cubeful Equities:
 No double:     +0,500 (-0,500)
 Double/Take:   +1,000
 Double/Pass:   +1,000
Best Cube action: Double / Take</code></pre>
</div>
</div>
</div>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/pos2-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Player Winning Chances:   77,93% (G:0,00% B:0,00%)
Opponent Winning Chances: 22,07% (G:0,00% B:0,00%)
Cubeless Equities: No Double=+0,559, Double=+1,117
Cubeful Equities:
 No double:     +0,838 (-0,144)
 Double/Take:   +0,983
 Double/Pass:   +1,000 (+0,017)
Best Cube action: Double / Take</code></pre>
</div>
</div>
</div>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/pos3-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Player Winning Chances:   73,58% (G:14,79% B:0,70%)
Opponent Winning Chances: 26,42% (G:4,53% B:0,16%)
Cubeless Equities: No Double=+0,581, Double=+1,159
Cubeful Equities:
 No double:     +0,923 (-0,052)
 Double/Take:   +0,975
 Double/Pass:   +1,000 (+0,025)
Best Cube action: Double / Take</code></pre>
</div>
</div>
</div>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/pos4-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Player Winning Chances:   70,79% (G:23,06% B:1,12%)
Opponent Winning Chances: 29,21% (G:6,10% B:0,23%)
Cubeless Equities: No Double=+0,588, Double=+1,189
Cubeful Equities:
 No double:     +0,871 (-0,101)
 Double/Take:   +0,972
 Double/Pass:   +1,000 (+0,028)
Best Cube action: Double / Take</code></pre>
</div>
</div>
</div>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/pos5-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Player Winning Chances:   67,23% (G:35,78% B:0,95%)
Opponent Winning Chances: 32,77% (G:7,68% B:0,40%)
Cubeless Equities: No Double=+0,616, Double=+1,262
Cubeful Equities:
 No double:     +0,843 (-0,152)
 Double/Take:   +0,995
 Double/Pass:   +1,000 (+0,005)
Best Cube action: Double / Take</code></pre>
</div>
</div>
</div>
<p>We’ll use these as examples to consider how the score influences take points in a five-point match.</p>
</section>
<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>First, a high level overview of the scores we see in five-point matches.</p>
<section id="match-equity-table" class="level3">
<h3 class="anchored" data-anchor-id="match-equity-table">Match equity table</h3>
<p>For convenience, here’s the default match equity table used by XG, for five-point matches, rounded to three decimal points:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      1     2     3     4     5
1 0.500 0.677 0.751 0.814 0.842
2 0.323 0.500 0.599 0.669 0.744
3 0.249 0.401 0.500 0.572 0.648
4 0.186 0.331 0.428 0.500 0.577
5 0.158 0.256 0.352 0.423 0.500</code></pre>
</div>
</div>
</section>
<section id="take-point-plots" class="level3">
<h3 class="anchored" data-anchor-id="take-point-plots">Take point plots</h3>
<p>Plotting take points under different situations might help to build an intuition of the cube dynamics in the five-point match. We first calculate take points assuming the doubled player will never redouble (except for automatic redoubles when we have nothing to lose). This is to see the effect of the score and gammons, for now ignoring the cube.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="5-point-match_files/figure-html/plot1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Several patterns stand out; some well-know, some might not be so well-know. A few observations:</p>
<ul>
<li>The absolutely lowest take point you can face, is when leading 2-away, 5-away in a straight race. You can take here with as little as 17% winning chances.</li>
<li>Not surprisingly, if you get doubled at 4-away, 2-away, the automatic redouble to 4 also generates a low take point: 19%.</li>
<li>Leading 2-away, 4-away, get you the third-lowest race take point: 20%.</li>
<li>However, leading 2-away, <em>3</em>-away, makes for a slightly <em>higher</em> take point (26%) than for money, since winning two points is also very valuable for the opponent here.</li>
<li>Same thing at 4-away, 3-away; we have the very highest dead-cube race take point: 35%. (Note that this of course changes when we introduce the cube, since re-cubes are very potent here. But be careful if this is a last-roll situation).</li>
<li>The innocent 5-away 4-away is also dangerous: Take point 30%.</li>
<li>At the other end of the spectrum we see (not surprisingly) very high take points when the opponent needs 4 <em>and</em> has a clear gammon threat. Of course we have the notorious 2-away 4-away, where you need tremendous compensation in terms of winning chances, if you get doubled with a good risk of losing a gammon. But 3-away, 4-away and 5-away, 4-away, are almost as precarious.</li>
<li>In general, introducing gammons pushed the take points up, a good deal more than for money (compare the purple dots to the purple dotted line), because winning a gammon with the cube at two generally is pretty decisive in a 5-point match.</li>
</ul>
<p>Let’s focus on the effect of introducing the cube. If we look at a straight, medium length race, like in our reference position above, access to the cube in a money game generally allows us to take with about 22% rather than the 25% we would need in a true last roll situation.</p>
<p>At match scores, that effect varies considerably. Look at the plot below:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="5-point-match_files/figure-html/plot2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Of course, at scores where a double/take (and possibly an automatic re-cube) leaves the cube dead, there’s no difference between the dead-cube take point and the take point including the cube.</p>
<p>At other scores, in general, the cube benefits the trailer the most: At 4-away, 3-away, for example, cube access makes a massive difference, lowering the take point from 35% to 26%.</p>
<p>In contrast, at 3-away, 5-away, if the leader redoubles, the cube comes back at 8, making his lead meaningless, so being able to redouble is not so helpful. Take point goes from 21% cubeless to 19% with cube leverage. (Both lower than the money take point of 22%, however.)</p>
</section>
</section>
<section id="pre-crawford" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="pre-crawford">Pre-crawford</h2>
<section id="away-scores" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="away-scores">5-away scores</h3>
<section id="away-5-away" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="away-5-away">5-away, 5-away</h4>
<p>We give this score a pretty detailed treatment, then apply the same methodology to the rest of the pre-Crawford scores. The intention is to examine the anatomy of all scores: How are they different from money <em>in general</em>?</p>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Estimated live cube take points at 5-away, 5-away, cube at 1</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Position type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, match</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, money</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Last roll</td>
<td style="text-align: right;">0.239</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">-0.011</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race</td>
<td style="text-align: right;">0.201</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">-0.014</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A little gammon</td>
<td style="text-align: right;">0.262</td>
<td style="text-align: right;">0.261</td>
<td style="text-align: right;">0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Some gammons</td>
<td style="text-align: right;">0.297</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: right;">0.006</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Many gammons</td>
<td style="text-align: right;">0.344</td>
<td style="text-align: right;">0.335</td>
<td style="text-align: right;">0.010</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>This table compares take point for the five example positions for money and at the score 5-away, 5-away. When the difference between the match and the money take point is negative, it means the position is easier to take at the match score. When the difference is positive, we have less of a take at the score.</p>
<p>Let’s spot check with a few rollouts at the score: Our sample race position and the blitz position:</p>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/pos2-5a5a-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, cubeful equities:
 No double:     +0,838 (-0,144)
 Double/Take:   +0,983
 Double/Pass:   +1,000 (+0,017)

5-away, 5-away, cubeful equities:
 No double:     +0,817 (-0,093)
 Double/Take:   +0,910
 Double/Pass:   +1,000 (+0,090)</code></pre>
</div>
</div>
</div>
<p>The rollout confirms that this race is indeed a bigger take at the score, as we would expect from the slightly lower take point.</p>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/pos5-5a5a-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, cubeful equities:
 No double:     +0,843 (-0,152)
 Double/Take:   +0,995
 Double/Pass:   +1,000 (+0,005)

5-away, 5-away, cubeful equities:
 No double:     +0,856 (-0,144)
 Double/Take:   +1,096 (+0,096)
 Double/Pass:   +1,000</code></pre>
</div>
</div>
</div>
<p>Again, the rollout shows that the blitz position, which was a marginal take for money, is a pass at the score, due to the slightly higher take point.</p>
<p>Lee’s do the rest of the scores, using the same kind of table for displaying take poins and how much they differ for money, but fresh example positions.</p>
</section>
<section id="away-5-away-1" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="away-5-away-1">4-away, 5-away</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Estimated live cube take points at 4-away, 5-away, cube at 1</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Position type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, match</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, money</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Last roll</td>
<td style="text-align: right;">0.227</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">-0.023</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race</td>
<td style="text-align: right;">0.188</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">-0.026</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A little gammon</td>
<td style="text-align: right;">0.265</td>
<td style="text-align: right;">0.261</td>
<td style="text-align: right;">0.004</td>
</tr>
<tr class="even">
<td style="text-align: left;">Some gammons</td>
<td style="text-align: right;">0.305</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: right;">0.014</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Many gammons</td>
<td style="text-align: right;">0.359</td>
<td style="text-align: right;">0.335</td>
<td style="text-align: right;">0.025</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li><p>Winning two points and getting to 2-away is valuable, so take point is lower that for money in last-roll or race positions.</p></li>
<li><p>Losing a gammon hurts extra, so take points rise as the opponents gammon threat rises.</p></li>
</ul>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No double:     +0,745 (-0,255)
 Double/Take:   +1,064 (+0,064)
 Double/Pass:   +1,000

4-away, 5-away, Cubeful Equities:
 No double:     +0,745 (-0,225)
 Double/Take:   +0,970
 Double/Pass:   +1,000 (+0,030)</code></pre>
</div>
</div>
</div>
<p>This is slightly better that a pure 3-roll position (that yields 21.2% winning chances) because Black is not gin after 22 and 11. Still a moderate pass for money, but a small take at the score.</p>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No double:     +0,784 (-0,171)
 Double/Take:   +0,955
 Double/Pass:   +1,000 (+0,045)

4-away, 5-away, Cubeful Equities:
 No double:     +0,801 (-0,199)
 Double/Take:   +1,138 (+0,138)
 Double/Pass:   +1,000</code></pre>
</div>
</div>
</div>
<p>Facing a very clear gammon threat, White has a big pass at the score, even though this is a moderate take for money.</p>
</section>
<section id="away-5-away-2" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="away-5-away-2">3-away, 5-away</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Estimated live cube take points at 3-away, 5-away, cube at 1</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Position type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, match</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, money</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Last roll</td>
<td style="text-align: right;">0.209</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">-0.041</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race</td>
<td style="text-align: right;">0.187</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">-0.027</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A little gammon</td>
<td style="text-align: right;">0.275</td>
<td style="text-align: right;">0.261</td>
<td style="text-align: right;">0.014</td>
</tr>
<tr class="even">
<td style="text-align: left;">Some gammons</td>
<td style="text-align: right;">0.320</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: right;">0.029</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Many gammons</td>
<td style="text-align: right;">0.379</td>
<td style="text-align: right;">0.335</td>
<td style="text-align: right;">0.044</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li><p>Winning 2 points is very valuable when 3-away; it gets you to the Crawford game. Therefore, take points in last-roll and race positions are low.</p></li>
<li><p>Recube vig is low, however, so the difference from money is most pronounced is pure last-roll positions where the cube is dead anyway.</p></li>
<li><p>Gammons are dangerous, so cation is required more and more as the likelihood of losing a gammon increases.</p></li>
</ul>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>




Money game, Cubeful Equities:
 No double:     +0,886 (-0,114)
 Double/Take:   +1,095 (+0,095)
 Double/Pass:   +1,000
 
3-away, 5-away, Cubeful Equities:
 No double:     +0,845 (-0,128)
 Double/Take:   +0,972
 Double/Pass:   +1,000 (+0,028)</code></pre>
</div>
</div>
</div>
<p>Down 7 pips, 42 vs.&nbsp;35, is a lot, even if Black has more vastage. But a bare take when you need three points to win.</p>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No double:     +0,761 (-0,070)
 Double/Take:   +0,832
 Double/Pass:   +1,000 (+0,168)

3-away, 5-away, Cubeful Equities:
 No double:     +0,895 (-0,105)
 Double/Take:   +1,088 (+0,088)
 Double/Pass:   +1,000</code></pre>
</div>
</div>
</div>
<p>Gammons changes the matter. To illustrate, this table of gammon values shows how much doubling <em>decreases</em> gammon values for the leader and <em>increases</em> gammon values for the trailer, leading to higher take points for the leader whenever gammons are at play.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Gammon values at 3-away, 5-away</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Cube value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Gammon value, 3-away</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Gammon value, 5-away</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.57</td>
<td style="text-align: right;">0.42</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.46</td>
<td style="text-align: right;">0.73</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
</section>
<section id="away-5-away-3" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="away-5-away-3">2-away, 5-away</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Estimated live cube take points at 2-away, 5-away, cube at 1</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Position type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, match</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, money</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Last roll</td>
<td style="text-align: right;">0.173</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">-0.077</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race</td>
<td style="text-align: right;">0.173</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">-0.041</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A little gammon</td>
<td style="text-align: right;">0.279</td>
<td style="text-align: right;">0.261</td>
<td style="text-align: right;">0.018</td>
</tr>
<tr class="even">
<td style="text-align: left;">Some gammons</td>
<td style="text-align: right;">0.332</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: right;">0.041</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Many gammons</td>
<td style="text-align: right;">0.400</td>
<td style="text-align: right;">0.335</td>
<td style="text-align: right;">0.066</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li>Same pattern as in 4-away, 5-away and in 3-away, 5-away, but even more pronounced: White takes more in races, considerable less in gammonish positions.</li>
</ul>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No double:     +0,748 (-0,252)
 Double/Take:   +1,251 (+0,251)
 Double/Pass:   +1,000

2-away, 5-away, Cubeful Equities:
 No double:     +0,689 (-0,283)
 Double/Take:   +0,972
 Double/Pass:   +1,000 (+0,028)</code></pre>
</div>
</div>
</div>
<p>Even in a slightly desperate close-to-last-roll situation White can find a take when two points wins exactly.</p>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No double:     +0,602 (-0,135)
 Double/Take:   +0,736
 Double/Pass:   +1,000 (+0,264)

2-away, 5-away, Cubeful Equities:
 No double:     +0,664 (-0,336)
 Double/Take:   +1,170 (+0,170)
 Double/Pass:   +1,000</code></pre>
</div>
</div>
</div>
<p>This is a bit scary since White can easily get closed out and gammoned. Still only 11 rolls cover the 4-point blot, and on the remaining 25 rolls White will have plenty of play if he just enters. Even after Blacks 7 rolls with hitting 3’s (43 and 63 don’t hit), entering gives White counter play. Easy take for money. At 2-away, 5-away it is a big pass, however.</p>
</section>
<section id="away-4-away" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="away-4-away">5-away, 4-away</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Estimated live cube take points at 5-away, 4-away, cube at 1</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Position type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, match</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, money</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Last roll</td>
<td style="text-align: right;">0.304</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">0.054</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race</td>
<td style="text-align: right;">0.243</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">0.029</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A little gammon</td>
<td style="text-align: right;">0.301</td>
<td style="text-align: right;">0.261</td>
<td style="text-align: right;">0.039</td>
</tr>
<tr class="even">
<td style="text-align: left;">Some gammons</td>
<td style="text-align: right;">0.333</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: right;">0.042</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Many gammons</td>
<td style="text-align: right;">0.380</td>
<td style="text-align: right;">0.335</td>
<td style="text-align: right;">0.045</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li><p>As opposed to the reverse score, 4-away, 5-away, the potential two points at stake now benefits the doubling player more, so the trailer faces higher take points <em>no matter</em> the type of position.</p></li>
<li><p>This is because <em>both</em> a two-point win and a four-point gammon win is particular valuable to the leader.</p></li>
</ul>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No double:     +0,475 (-0,475)
 Double/Take:   +0,951
 Double/Pass:   +1,000 (+0,049)

5-away, 4-away, Cubeful Equities:
 No double:     +0,505 (-0,495)
 Double/Take:   +1,110 (+0,110)
 Double/Pass:   +1,000</code></pre>
</div>
</div>
</div>
<p>Standard take for money, even with just <span class="math inline">\(\frac{10}{36}\times\frac{26}{36}\approx 0.201\)</span> winning probability since White has a strong recube on Blacks misses.</p>
<p>At the score recubes are even stronger: Black will need 0.298 to take the recube so must pass in case of a miss. That means Whites chances are effectively <span class="math inline">\(\frac{10}{36}\approx 0.278\)</span> – but still falling short of the 0.304 last-roll take point. `</p>
<p>The two points Black threatens to win are so valuable, that White has a clear pass.</p>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No double:     +0,866 (-0,008)
 Double/Take:   +0,874
 Double/Pass:   +1,000 (+0,126)
 
5-away, 4-away, Cubeful Equities:
 No double:     +0,912 (-0,088)
 Double/Take:   +1,058 (+0,058)
 Double/Pass:   +1,000</code></pre>
</div>
</div>
</div>
<p>Even this contact position with a position advantage but no particular gammon threat, is a small pass at the score, despite being only a very small double for money.</p>
</section>
<section id="away-3-away" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="away-3-away">5-away, 3-away</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Estimated live cube take points at 5-away, 3-away, cube at 1</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Position type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, match</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, money</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Last roll</td>
<td style="text-align: right;">0.287</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">0.037</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race</td>
<td style="text-align: right;">0.223</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">0.009</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A little gammon</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">0.261</td>
<td style="text-align: right;">-0.011</td>
</tr>
<tr class="even">
<td style="text-align: left;">Some gammons</td>
<td style="text-align: right;">0.270</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: right;">-0.021</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Many gammons</td>
<td style="text-align: right;">0.301</td>
<td style="text-align: right;">0.335</td>
<td style="text-align: right;">-0.034</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li><p>In a last roll position White still has a high take point at 0.287, because two points are very valuable for Black – getting him to the Crawford game</p></li>
<li><p>The race is different, because White now has a lot of cube leverage: White now has almost the same take point as for money.</p></li>
<li><p>Like we saw at 3-away, 5-away, the effect of gammons is to <em>lower</em> the take point for the trailer. This is because after double/take the gammon value <em>decreases</em> for the leader, and <em>increases</em> for the trailer.</p></li>
</ul>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No double:     +0,444 (-0,444)
 Double/Take:   +0,889
 Double/Pass:   +1,000 (+0,111)

5-away, 3-away, Cubeful Equities:
 No double:     +0,444 (-0,556)
 Double/Take:   +1,038 (+0,038)
 Double/Pass:   +1,000</code></pre>
</div>
</div>
</div>
<p>With no recube vig and no gammons, White has a high take point, turning this last-roll position from a clear money take to a small pass.</p>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No double:     +0,840 (-0,143)
 Double/Take:   +0,983
 Double/Pass:   +1,000 (+0,017)

5-away, 3-away, Cubeful Equities:
 No double:     +0,846 (-0,154)
 Double/Take:   +1,000
 Double/Pass:   +1,000 (+0,000)</code></pre>
</div>
</div>
</div>
<p>In our sample race position cube action is very similar for money and at the score: Whites extra recube vig offsets the higher take point to begin with.</p>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No double:     +0,818 (-0,182)
 Double/Take:   +1,062 (+0,062)
 Double/Pass:   +1,000

5-away, 3-away, Cubeful Equities:
 No double:     +0,716
 Double/Take:   +0,699 (-0,017)
 Double/Pass:   +1,000 (+0,284)
 
1296 Games rolled with Variance Reduction.
Moves: 3-ply, cube decisions: XG Roller</code></pre>
</div>
</div>
</div>
<p>Typical blitz position, a pass for money, turns into a big take, mainly because of changes in gammon values. It’s not <em>just</em> the cube leverage that makes the difference, because as we saw above, a race recube would have a take point for Black not too different from money game.</p>
<p>Gammon values, as we also saw earlier:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Gammon values at 5-away, 3-away</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Cube value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Gammon value, 5-away</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Gammon value, 3-away</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.42</td>
<td style="text-align: right;">0.57</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.73</td>
<td style="text-align: right;">0.46</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
</section>
<section id="away-2-away" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="away-2-away">5-away, 2-away</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Estimated live cube take points at 5-away, 2-away, cube at 1</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Position type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, match</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, money</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Last roll</td>
<td style="text-align: right;">0.395</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">0.145</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race</td>
<td style="text-align: right;">0.234</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">0.019</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A little gammon</td>
<td style="text-align: right;">0.216</td>
<td style="text-align: right;">0.261</td>
<td style="text-align: right;">-0.045</td>
</tr>
<tr class="even">
<td style="text-align: left;">Some gammons</td>
<td style="text-align: right;">0.212</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: right;">-0.079</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Many gammons</td>
<td style="text-align: right;">0.210</td>
<td style="text-align: right;">0.335</td>
<td style="text-align: right;">-0.125</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li><p>Without recubes, the trailer’s take point is extremely high: a full 0.395.</p></li>
<li><p>Of course the one-sided benefit from automatic recube makes a big difference, but, perhaps surprisingly, still leaves the trailer with a slightly higher racing game take point than for money.</p></li>
<li><p>Gammons don’t hurt the trailer after a take; naturally this allows for much more liberal takes compared to money game.</p></li>
</ul>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No double:     +0,336 (-0,246)
 Double/Take:   +0,582
 Double/Pass:   +1,000 (+0,418)
 
 
5-away, 2-away, Cubeful Equities:
 No double:     +0,348 (-0,652)
 Double/Take:   +1,081 (+0,081)
 Double/Pass:   +1,000</code></pre>
</div>
</div>
</div>
<p>If White takes and Black misses, Black will pass the automatic redouble, so that doesn’t benefit White much, leaving him with a very high take point and a pass here, even though for money the take is trivial.</p>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No double:     +0,965 (-0,035)
 Double/Take:   +1,235 (+0,235)
 Double/Pass:   +1,000
 
 
5-away, 2-away, Cubeful Equities:
 No double:     +0,890 (-0,110)
 Double/Take:   +1,002 (+0,002)
 Double/Pass:   +1,000</code></pre>
</div>
</div>
</div>
<p>White wins about 22%, so big pass for money, due to some gammon losses. At 5-away, 2-away after double/take/redouble gammons don’t hurt, and White can win four points, Black only two. Intuitively this would lower White’s take point by a lot. But the cube is dead which pulls in the opposite direction, and Black’s two points are worth a lot. As we saw above, in a straight race White would need 23% to take which is only a bit less than the comparable 25% White would need to take for money with a dead cube.</p>
<p>Bottom line: White has a marginal take/pass decision. 22% is about what he needs, the occasional freak gammon <em>win</em> (probability about 3%) accounts for the difference from the mentioned 23% racing game dead cube take point.</p>
</section>
</section>
<section id="away-scores-1" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="away-scores-1">4-away scores</h3>
<section id="away-4-away-1" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="away-4-away-1">4-away, 4-away</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Estimated live cube take points at 4-away, 4-away, cube at 1</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Position type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, match</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, money</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Last roll</td>
<td style="text-align: right;">0.288</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">0.038</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race</td>
<td style="text-align: right;">0.224</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">0.010</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A little gammon</td>
<td style="text-align: right;">0.299</td>
<td style="text-align: right;">0.261</td>
<td style="text-align: right;">0.038</td>
</tr>
<tr class="even">
<td style="text-align: left;">Some gammons</td>
<td style="text-align: right;">0.338</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: right;">0.047</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Many gammons</td>
<td style="text-align: right;">0.392</td>
<td style="text-align: right;">0.335</td>
<td style="text-align: right;">0.057</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li><p>Here <em>all</em> take points are higher than for money. This is because both a two-point and a four-point win is particular valuable. Doubling, in effect, <em>more</em> than doubles the stakes.</p></li>
<li><p>This also makes future <em>redoubles</em> more potent, which is why the smallest difference from money is in straight races: The taker gets powerful recubes but does not need to fear expensive gammon losses.</p></li>
</ul>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No double:     +0,591
 Double/Take:   +0,547 (-0,044)
 Double/Pass:   +1,000 (+0,409)

4-away, 4-away, Cubeful Equities:
 No double:     +0,682 (-0,135)
 Double/Take:   +0,817
 Double/Pass:   +1,000 (+0,183)</code></pre>
</div>
</div>
</div>
<p>This is one of the weaker variations on an opening 55 blitz: 65 followed by 55. Not quite a double for money, but a strong double at the score. White has a fine take though; the score calls for caution, not panic.</p>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No double:     +0,563 (-0,145)
 Double/Take:   +0,707
 Double/Pass:   +1,000 (+0,293)

4-away, 4-away, Cubeful Equities:
 No double:     +0,630 (-0,370)
 Double/Take:   +1,079 (+0,079)
 Double/Pass:   +1,000</code></pre>
</div>
</div>
</div>
<p>Highly volatile position, which makes for a good double for money, but clear take. White could get gammoned (about 26% of the time) but also wins 35% of the games. At the score, this is too much, White has a moderate pass.</p>
</section>
<section id="away-4-away-2" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="away-4-away-2">3-away, 4-away</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Estimated live cube take points at 3-away, 4-away, cube at 1</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Position type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, match</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, money</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Last roll</td>
<td style="text-align: right;">0.240</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">-0.010</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race</td>
<td style="text-align: right;">0.211</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">-0.004</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A little gammon</td>
<td style="text-align: right;">0.312</td>
<td style="text-align: right;">0.261</td>
<td style="text-align: right;">0.051</td>
</tr>
<tr class="even">
<td style="text-align: left;">Some gammons</td>
<td style="text-align: right;">0.361</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: right;">0.070</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Many gammons</td>
<td style="text-align: right;">0.426</td>
<td style="text-align: right;">0.335</td>
<td style="text-align: right;">0.091</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li><p>Here, the two points are more valuable for the leader than the trailer, so the ‘raw’ take point (cubeless, gammonless) is slightly lower than for money.</p></li>
<li><p>Gammons are very dangerous, of course.</p></li>
</ul>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No double:     +0,591
 Double/Take:   +0,547 (-0,044)
 Double/Pass:   +1,000 (+0,409)

3-away, 4-away, Cubeful Equities:
 No double:     +0,819 (-0,181)
 Double/Take:   +1,139 (+0,139)
 Double/Pass:   +1,000</code></pre>
</div>
</div>
</div>
<p>Our 65-55-opening blitz from before (small no double for money), is now a clear pass. The combination of a lethal gammon threat and limited recube potential is just too much.</p>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No double:     +0,877 (-0,046)
 Double/Take:   +0,923
 Double/Pass:   +1,000 (+0,077)

3-away, 4-away, Cubeful Equities:
 No double:     +0,975 (-0,025)
 Double/Take:   +1,436 (+0,436)
 Double/Pass:   +1,000</code></pre>
</div>
</div>
</div>
<p>Sound money double in this artificial position, based on big positional advantage (not on volatility). The combinations of gammon threat and low cube value makes this a huge pass at the score.</p>
</section>
<section id="away-4-away-3" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="away-4-away-3">2-away, 4-away</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Estimated live cube take points at 2-away, 4-away, cube at 1</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Position type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, match</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, money</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Last roll</td>
<td style="text-align: right;">0.199</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">-0.051</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race</td>
<td style="text-align: right;">0.199</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">-0.015</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A little gammon</td>
<td style="text-align: right;">0.333</td>
<td style="text-align: right;">0.261</td>
<td style="text-align: right;">0.072</td>
</tr>
<tr class="even">
<td style="text-align: left;">Some gammons</td>
<td style="text-align: right;">0.396</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: right;">0.105</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Many gammons</td>
<td style="text-align: right;">0.477</td>
<td style="text-align: right;">0.335</td>
<td style="text-align: right;">0.142</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li>Same pattern as for 4-away, 4-away, and for 3-away, 4-away, but a lot stronger: It’s relatively easy to take in no-gammon situations; very hard when a significant gammon threat exists.</li>
</ul>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No double:     +0,681 (-0,319)
 Double/Take:   +1,119 (+0,119)
 Double/Pass:   +1,000

2-away, 4-away, Cubeful Equities:
 No double:     +0,656 (-0,298)
 Double/Take:   +0,954
 Double/Pass:   +1,000 (+0,046)</code></pre>
</div>
</div>
</div>
<p>This 21% position is a fine take when we need only 20% to take.</p>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No double:     +0,405
 Double/Take:   +0,258 (-0,147)
 Double/Pass:   +1,000 (+0,595)

2-away, 4-away, Cubeful Equities:
 No double:     +0,800 (-0,184)
 Double/Take:   +0,984
 Double/Pass:   +1,000 (+0,016)</code></pre>
</div>
</div>
</div>
<p>The slightest smell of blitz, makes for at best a marginal take at 4-away, 2-away.</p>
</section>
<section id="away-3-away-1" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="away-3-away-1">4-away, 3-away</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Estimated live cube take points at 4-away, 3-away, cube at 1</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Position type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, match</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, money</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Last roll</td>
<td style="text-align: right;">0.352</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">0.102</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race</td>
<td style="text-align: right;">0.258</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">0.044</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A little gammon</td>
<td style="text-align: right;">0.279</td>
<td style="text-align: right;">0.261</td>
<td style="text-align: right;">0.018</td>
</tr>
<tr class="even">
<td style="text-align: left;">Some gammons</td>
<td style="text-align: right;">0.297</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: right;">0.006</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Many gammons</td>
<td style="text-align: right;">0.325</td>
<td style="text-align: right;">0.335</td>
<td style="text-align: right;">-0.010</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li>Even trailing, it’s somewhat difficult to find a take at this score – except when gammons are clearly visible.</li>
</ul>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No double:     +0,711 (-0,026)
 Double/Take:   +0,737
 Double/Pass:   +1,000 (+0,263)

4-away, 3-away, Cubeful Equities:
 No double:     +0,918 (-0,082)
 Double/Take:   +1,129 (+0,129)
 Double/Pass:   +1,000</code></pre>
</div>
</div>
</div>
<p>A five-roll position is a solid pass at the score.</p>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No double:     +0,879 (-0,083)
 Double/Take:   +0,962
 Double/Pass:   +1,000 (+0,038)

4-away, 3-away, Cubeful Equities:
 No double:     +0,839 (-0,049)
 Double/Take:   +0,887
 Double/Pass:   +1,000 (+0,113)</code></pre>
</div>
</div>
</div>
<p>Solid positional advantage, gammons clearly a relevant consideration, so small money take becomes a clear take at 4-away, 3-away.</p>
</section>
<section id="away-2-away-1" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="away-2-away-1">4-away, 2-away</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Estimated live cube take points at 4-away, 2-away, cube at 1</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Position type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, match</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, money</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Last roll</td>
<td style="text-align: right;">0.371</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">0.121</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race</td>
<td style="text-align: right;">0.186</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">-0.029</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A little gammon</td>
<td style="text-align: right;">0.186</td>
<td style="text-align: right;">0.261</td>
<td style="text-align: right;">-0.075</td>
</tr>
<tr class="even">
<td style="text-align: left;">Some gammons</td>
<td style="text-align: right;">0.186</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: right;">-0.105</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Many gammons</td>
<td style="text-align: right;">0.186</td>
<td style="text-align: right;">0.335</td>
<td style="text-align: right;">-0.149</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li><p>With the perfect automatic recube available the trailer can of course take with 19% – the winning chance we get when passing for 4-away, 1-away, Crawford.</p></li>
<li><p>The last-roll situation, where we don’t get to the automatic recube, is a trap; here the take point is a very high 37%</p></li>
</ul>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No double:     +0,517 (-0,460)
 Double/Take:   +0,976
 Double/Pass:   +1,000 (+0,024)

4-away, 3-away Cubeful Equities:
 No double:     +0,654 (-0,346)
 Double/Take:   +1,010 (+0,010)
 Double/Pass:   +1,000</code></pre>
</div>
</div>
</div>
<p>If Black misses, 12/36, he will pass the automatic recube, so White really wins 1/3 plus about 3% after getting hit, roughly 35% in total, which is just a bit short of a take. For money, the problem is that White can lose a gammon after getting hit, but he is getting better odds on the take, and so bottomline is a small take.</p>
<p>So a close take/pass decision both at 4-away, 2-away and money, but for different reasons.</p>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No double:     +1,072
 Double/Take:   +1,847 (+0,775)
 Double/Pass:   +1,000 (-0,072)

4-away, 2-away, Cubeful Equities:
 No double:     +1,062
 Double/Take:   +0,758 (-0,303)
 Double/Pass:   +1,000 (-0,062)</code></pre>
</div>
</div>
</div>
<p>Another tricky one: Clearly a gigantic pass for money, moderately too good to double. At the score Black also should play for the gammon which seems quite intuitive. But if doubled, White has a moderate take, because of the low take point. In that sense, the position is both too good and not good enough: If Black doubles he is worse off whether White passes or takes.</p>
</section>
</section>
<section id="away-scores-2" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="away-scores-2">3-away scores</h3>
<section id="away-3-away-2" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="away-3-away-2">3-away, 3-away</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Estimated live cube take points at 3-away, 3-away, cube at 1</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Position type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, match</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, money</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Last roll</td>
<td style="text-align: right;">0.302</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">0.052</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race</td>
<td style="text-align: right;">0.252</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">0.037</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A little gammon</td>
<td style="text-align: right;">0.296</td>
<td style="text-align: right;">0.261</td>
<td style="text-align: right;">0.035</td>
</tr>
<tr class="even">
<td style="text-align: left;">Some gammons</td>
<td style="text-align: right;">0.322</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: right;">0.031</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Many gammons</td>
<td style="text-align: right;">0.361</td>
<td style="text-align: right;">0.335</td>
<td style="text-align: right;">0.026</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li><p>At 3-away, 3-away it is harder to find a take in all position types.</p></li>
<li><p>On one hand, two points are very valuable – the double more than doubles the stakes – so in the last-roll starting point the take point is quite a bit higher than for money.</p></li>
<li><p>On the other hand, the cube leverage is a little better than for money, so some of the difference disappears when we allow for redoubles.</p></li>
<li><p>Also note that the gammon value <em>before</em> doubling is very high, after double/take the gammon value is similar to money game:</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Gammon values at 3-away, 3-away</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Cube value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Gammon value, 3-away</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.76</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.50</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No double:     +0,802 (-0,082)
 Double/Take:   +0,883
 Double/Pass:   +1,000 (+0,117)

3-away, 3-away, Cubeful Equities:
 No double:     +0,865 (-0,135)
 Double/Take:   +1,052 (+0,052)
 Double/Pass:   +1,000</code></pre>
</div>
</div>
</div>
<p>Black leads in every area, including the important race, so solid double/take for money. But 3-away, 3-away pushes this into double/pass territory.</p>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No double:     +0,881 (-0,072)
 Double/Take:   +0,953
 Double/Pass:   +1,000 (+0,047)

3,away,3-away, Cubeful Equities:
 No double:     +0,975 (-0,025)
 Double/Take:   +1,171 (+0,171)
 Double/Pass:   +1,000
 
1296 Games rolled with Variance Reduction.
Moves: 3-ply, cube decisions: XG Roller</code></pre>
</div>
</div>
</div>
<p>A pretty standard holding game, take for money, becomes a big pass at 3-away, 3-away.</p>
<p>(Note that this is rolled out, instead of using XG++ like we did most other places. Even the truncated rollout in XG++ overestimates holding games.)</p>
</section>
<section id="away-3-away-3" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="away-3-away-3">2-away, 3-away</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Estimated live cube take points at 2-away, 3-away, cube at 1</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Position type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, match</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, money</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Last roll</td>
<td style="text-align: right;">0.262</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">0.012</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race</td>
<td style="text-align: right;">0.262</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">0.048</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A little gammon</td>
<td style="text-align: right;">0.326</td>
<td style="text-align: right;">0.261</td>
<td style="text-align: right;">0.065</td>
</tr>
<tr class="even">
<td style="text-align: left;">Some gammons</td>
<td style="text-align: right;">0.361</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: right;">0.070</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Many gammons</td>
<td style="text-align: right;">0.411</td>
<td style="text-align: right;">0.335</td>
<td style="text-align: right;">0.076</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li><p>Every type of position is a bit harder to take here than for money, although the difference is less pronounced in last-roll positions where White wouldn’t have had the benefit of potential redoubles anyway.</p></li>
<li><p>Of course, <em>especially</em> when the trailer has a gammon threat, the leader should be reluctant to take.</p></li>
</ul>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>




Money game, Cubeful Equities:
 No double:     +0,764 (-0,141)
 Double/Take:   +0,906
 Double/Pass:   +1,000 (+0,094)

2-away, 3-away, Cubeful Equities:
 No double:     +0,767 (-0,233)
 Double/Take:   +1,037 (+0,037)
 Double/Pass:   +1,000</code></pre>
</div>
</div>
</div>
<p>In this 4-roll position 11 doesn’t necessarily save a roll for White, so White is a bit worse off compared to a pure 4-roll position. Enough to turn a money take into a pass at the score.</p>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>




Money game, Cubeful Equities:
 No double:     +0,784 (-0,171)
 Double/Take:   +0,955
 Double/Pass:   +1,000 (+0,045)
 
 
2-away, 3-away, Cubeful Equities:
 No double:     +1,030
 Double/Take:   +1,451 (+0,421)
 Double/Pass:   +1,000 (-0,030)       </code></pre>
</div>
</div>
</div>
<p>When Black has a match winning gammon threat, this small money take becomes a gigantic pass at 2-away, 3-away</p>
</section>
<section id="away-2-away-2" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="away-2-away-2">3-away, 2-away</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Estimated live cube take points at 3-away, 2-away, cube at 1</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Position type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, match</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, money</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Last roll</td>
<td style="text-align: right;">0.368</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">0.118</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race</td>
<td style="text-align: right;">0.249</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">0.035</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A little gammon</td>
<td style="text-align: right;">0.249</td>
<td style="text-align: right;">0.261</td>
<td style="text-align: right;">-0.012</td>
</tr>
<tr class="even">
<td style="text-align: left;">Some gammons</td>
<td style="text-align: right;">0.249</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: right;">-0.042</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Many gammons</td>
<td style="text-align: right;">0.249</td>
<td style="text-align: right;">0.335</td>
<td style="text-align: right;">-0.085</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li><p>Naturally, the trailer can take (and redouble) with anything better than the 24.9% he would have had after passing and getting to 3-away, 1-away, Crawford.</p></li>
<li><p>Beware the last-roll situation, however: When the leader could win exactly 2-point (and not risk losing 3 or 4 point) that is dangerous.</p></li>
</ul>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>




Money game, Cubeful Equities:
 No double:     +0,278 (-0,278)
 Double/Take:   +0,556
 Double/Pass:   +1,000 (+0,444)

3-away, 2-away, Cubeful Equities:
 No double:     +0,278 (-0,722)
 Double/Take:   +1,037 (+0,037)
 Double/Pass:   +1,000</code></pre>
</div>
</div>
</div>
<p>Even with 36.1% winning chances White can’t quite take at the score with no automatic recube available; he needs 36.8%.</p>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>




Money game, Cubeful Equities:
 No double:     +0,764 (-0,141)
 Double/Take:   +0,906
 Double/Pass:   +1,000 (+0,094)
 
3-away, 2-away, Cubeful Equities:
 No double:     +0,766 (-0,188)
 Double/Take:   +0,954
 Double/Pass:   +1,000 (+0,046)</code></pre>
</div>
</div>
</div>
<p>The same near-four-roll position as shown to be a pass at 2-away, 3-away. A smallish take at this score.</p>
</section>
</section>
<section id="the-funny-two-point-match" class="level3">
<h3 class="anchored" data-anchor-id="the-funny-two-point-match">The funny two-point match</h3>
<p>The two-point match is funny: It’s a well-known fact that an optimal strategy is to double at first opportunity, at which point the opponent will always have a clear take, with the take point being 32%.</p>
<p>However, in practice, if you delay doubling until you have at least one market losing sequence, you might gain a bit from either:</p>
<ol type="a">
<li>The opponent doubling too late and loosing their market</li>
<li>The opponent passing a less obvious take</li>
</ol>
<p>On the flip side, delaying doubling may cost you if:</p>
<ol type="a">
<li>You accidentally lose your market by overlooking something</li>
<li>You end up passing what is really a take.</li>
</ol>
<p>For example, let’s say the opponent opens with 31. Should you double, knowing there’s zero chance he will pass? The best possible sequence is that you roll 66 and he rolls 61, which will still leave him with more than 40% winning chances and a very clear take. Still, the take is less clear than before, so perhaps there’s someone out there that will pass.</p>
<p>In practical play, it would be better to roll in response to an opening 31, since it can’t hurt and it opens the possibility of harvesting a mistake the opponent might make.</p>
<p>Suppose it is you who opens the game with 31, an he rolls 52, splitting. Now you <em>do</em> have market losers: Mostly involving you rolling 33, 55, or 66 and him responding poorly. Against any particular opponent it <em>might</em> still be the best play to hold off, but that depends on exactly how likely you are to lose your market (and by how much), and exactly how more likely the opponent is to make a future mistake, compare to yourself. That’s extremely hard to judge, so the best practical play against reasonably competent opposition, is probably to double.</p>
</section>
</section>
<section id="post-crawford" class="level2">
<h2 class="anchored" data-anchor-id="post-crawford">Post-crawford</h2>
<section id="away-even-away" class="level3">
<h3 class="anchored" data-anchor-id="away-even-away">1-away, even-away</h3>
<p>When you are leading post-crawford, with the opponent being either 2-away or 4-away, you have a ‘free drop’. At 1-away, 2-away you can pass and get to double match point for 50% winning chances, so you need to have better than that to take.</p>
<p>In general, you pass if you win the opening with one of the poorer rolls: 51, 52, or 43. Naturally you pass most of the time when the opponents win the opening roll – unless you respond strong, for example by hitting.</p>
<p>At 1-away, 4-away you can take slightly more, the idea being of ‘saving’ the free drop for later, if you lose a single game and get to 1-away, 2-away, where you might need the free pass even more – like if the opponent opens with 31 and you don’t roll a good double (11, 33, 66 will do the trick) in return.</p>
<p>A good benchmark: If you open with 41, played 13/9, 24/23, you should <em>pass</em> at 1-away, 2-away, but <em>take</em> at 1-away, 4-away.</p>
</section>
<section id="even-away-1-away" class="level3">
<h3 class="anchored" data-anchor-id="even-away-1-away">Even-away, 1-away</h3>
<p>When trailing 2-away or 4-away, of course you double right away. If you have no market losers that would make you a favorite, you <em>could</em> delay doubling, hoping to double and induce a wrong pass if you become a near-favorite. But this won’t really work: You would need a position good enough so that becoming a near-favorite is possible, but becoming an actual favorite is not possible. Even after a sequence like 54 (split), 44 (point-on-head) you could roll a joker like 11 from the bar, potentially losing your market.</p>
</section>
<section id="away-odd-away" class="level3">
<h3 class="anchored" data-anchor-id="away-odd-away">1-away, odd-away</h3>
<p>At 1-away, 3-away or 1-away, 5-away, you have a ‘free take’. How free is ‘free’?</p>
<p>If, at 1-away, 3-away, you pass you get to 1-away, 2-away were you have the benefit of a free drop, making your match winning chances slightly above even-money: 51.2%. By taking and losing you get to DMP for 50%, so the loss is just 1.2%. The gain from taking and winning is 48.8%, making the take point:</p>
<p><span class="math inline">\(Take\ point = \frac{loss}{loss+gain} = \frac{1.2}{1.2 + 48.8} = 2.4\)</span>%</p>
<p>At 1-away, 5-away, the corresponding numbers would look like this:</p>
<p><span class="math inline">\(Take\ point = \frac{loss}{loss+gain} = \frac{1.3}{1.3 + 32.3} = 3.9\)</span>%</p>
<p>So the take is indeed almost free – unless we can lose a gammon. Gammons are expensive, with a value of 1.0 after double/take at 1-away, 3-away, and 0.55 at 1-away, 3-away. This means that in the worst case (opponent 3-away) we can take when our gammon chances are no less than our winning chances.</p>
<p>When opponent is 5-away gammons are not nearly as costly, so they need to be roughly double our winning chances for us to pass.</p>
<p>For example, suppose we open with one of the worst possible sequences: 52 (split), then the opponent fails to double, rolls 55 (double hit), then we dance with both checkers with 66. Now we have roughly 30% chances of winning but 40% chanches of getting gammoned.</p>
<p>That is a big pass at 1-away, 3-away, and a big take at 1-away, 5-away.</p>
<p>So practically speaking: When we have a free take available we take almost everything, <em>except</em> when being blitzed real badly.</p>
</section>
<section id="odd-away-1-away" class="level3">
<h3 class="anchored" data-anchor-id="odd-away-1-away">Odd-away, 1-away</h3>
<p>The above analysis also means that when trailing, and the opponent have a free take, we can delay doubling with little risk, as long as we’re not really threatening to win a gammon.</p>
<p>For example, suppose we’re trailing 3-away post-crawford, and the opponent opens with 21: 13/11 6/5. We <em>could</em> double, expecting an automatic take (hoping for an enormous bonus if the opponent mistakes the free take for a free drop).</p>
<p><em>Or</em> we could roll, hoping for something like 64 (double hit), 66 (double dance), in which case the opponent will <em>still</em> have a clear take (winning about 37%, lossing a gammon about 27% of the time) – but might also have a lot harder decision with more room for mistaking an easy take for a drop.</p>
<p>The practical advice would be to double anything that looks like a blitz, and wait with anything that does not.</p>
</section>
</section>
<section id="recubes" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="recubes">Recubes</h2>
<section id="away-5-away-4" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="away-5-away-4">5-away, 5-away</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Estimated live cube take points at 5-away, 5-away, cube at 2</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Position type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, match</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, money</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Last roll</td>
<td style="text-align: right;">0.284</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">0.034</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race</td>
<td style="text-align: right;">0.254</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">0.039</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A little gammon</td>
<td style="text-align: right;">0.278</td>
<td style="text-align: right;">0.261</td>
<td style="text-align: right;">0.017</td>
</tr>
<tr class="even">
<td style="text-align: left;">Some gammons</td>
<td style="text-align: right;">0.294</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: right;">0.003</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Many gammons</td>
<td style="text-align: right;">0.318</td>
<td style="text-align: right;">0.335</td>
<td style="text-align: right;">-0.016</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li>At 5-away, 5-away it is little harder to find a take for a recube in positions without too many gammons, because the extra two points are particular valuable.</li>
<li>When gammons are likely, this effect is reduced, or even reversed, because after double/take the gammon drops low:</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Gammon values at 5-away, 5-away</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Cube value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Gammon value, 5-away</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.66</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.23</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-51-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No redouble:     +0,819 (-0,111)
 Redouble/Take:   +0,931
 Redouble/Pass:   +1,000 (+0,069)

5-away, 5-away, Cubeful Equities:
 No redouble:     +0,859 (-0,137)
 Redouble/Take:   +0,996
 Redouble/Pass:   +1,000 (+0,004)</code></pre>
</div>
</div>
</div>
<p>Case in point: A position with strong boards and some gammon potential for both sides, but not enough to reverse the small tendency to drop at the score: White has enough for a decent money-take for, but at best a very marginal take at the score.</p>
<p>It would take a truly gammonish position to make the underdog <em>more</em> inclined to take at the score, like our initial sample position for ‘many gammons’:</p>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No redouble:     +0,873 (-0,110)
 Redouble/Take:   +0,984
 Redouble/Pass:   +1,000 (+0,016)

5-away, 5-away, Cubeful Equities:
 No redouble:     +0,879 (-0,032)
 Redouble/Take:   +0,911
 Redouble/Pass:   +1,000 (+0,089)</code></pre>
</div>
</div>
</div>
<p>Ignoring that this position is too young to be a likely <em>re</em>double, Black is more inclined to take at the score, than for money.</p>
</section>
<section id="away-5-away-5" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="away-5-away-5">4-away, 5-away</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Estimated live cube take points at 4-away, 5-away, cube at 2</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Position type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, match</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, money</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Last roll</td>
<td style="text-align: right;">0.298</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">0.048</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race</td>
<td style="text-align: right;">0.298</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">0.084</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A little gammon</td>
<td style="text-align: right;">0.329</td>
<td style="text-align: right;">0.261</td>
<td style="text-align: right;">0.068</td>
</tr>
<tr class="even">
<td style="text-align: left;">Some gammons</td>
<td style="text-align: right;">0.347</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: right;">0.056</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Many gammons</td>
<td style="text-align: right;">0.374</td>
<td style="text-align: right;">0.335</td>
<td style="text-align: right;">0.039</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li><p>At 4-away, 5-away it is even harder for the leader to take a recube, and this holds across all position types, although the effect is smallest when a lot of gammons are in play.</p></li>
<li><p>The reason is of course, the the cube is now officially dead after redouble/take, <em>and</em> the gammon value drops all the way down to zero for the leader, but not quite as low for the trailer:</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Gammon values at 4-away, 5-away</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Cube value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Gammon value, 4-away</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Gammon value, 5-away</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.81</td>
<td style="text-align: right;">0.77</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.23</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No redouble:     +0,819 (-0,111)
 Redouble/Take:   +0,931
 Redouble/Pass:   +1,000 (+0,069)

4-away, 5-away, Cubeful Equities:
 No redouble:     +0,989 (-0,011)
 Redouble/Take:   +1,314 (+0,314)
 Redouble/Pass:   +1,000</code></pre>
</div>
</div>
</div>
<p>Example position 1, which was a marginal take at 5-away, 5-away, is now a huge drop.</p>
</section>
<section id="away-5-away-6" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="away-5-away-6">3-away, 5-away</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Estimated live cube take points at 3-away, 5-away, cube at 2</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Position type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, match</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, money</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Last roll</td>
<td style="text-align: right;">0.334</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">0.084</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race</td>
<td style="text-align: right;">0.334</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">0.120</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A little gammon</td>
<td style="text-align: right;">0.376</td>
<td style="text-align: right;">0.261</td>
<td style="text-align: right;">0.115</td>
</tr>
<tr class="even">
<td style="text-align: left;">Some gammons</td>
<td style="text-align: right;">0.399</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: right;">0.108</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Many gammons</td>
<td style="text-align: right;">0.434</td>
<td style="text-align: right;">0.335</td>
<td style="text-align: right;">0.099</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>Observations:</p>
<ul>
<li><p>Across all positions types it is <em>much</em> harder to take a redouble when leading 3-away, 5-away, compared to money.</p></li>
<li><p>This is one of the big reasons why it’s often a good idea to postpone the initial doubling a bit when leading 3-away, 5-away: It’s a powerful weapon you’re giving away.</p></li>
</ul>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-57-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No redouble:     +0,784 (-0,121)
 Redouble/Take:   +0,905
 Redouble/Pass:   +1,000 (+0,095)

3-away, 5-away, Cubeful Equities:
 No redouble:     +0,995 (-0,005)
 Redouble/Take:   +1,570 (+0,570)
 Redouble/Pass:   +1,000</code></pre>
</div>
</div>
</div>
<p>A pretty straight double/take for money, becomes a gigantic drop at the score.</p>
</section>
<section id="away-4-away-4" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="away-4-away-4">5-away, 4-away</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Estimated live cube take points at 5-away, 4-away, cube at 2</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Position type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, match</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, money</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Last roll</td>
<td style="text-align: right;">0.315</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">0.065</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race</td>
<td style="text-align: right;">0.256</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">0.042</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A little gammon</td>
<td style="text-align: right;">0.256</td>
<td style="text-align: right;">0.261</td>
<td style="text-align: right;">-0.005</td>
</tr>
<tr class="even">
<td style="text-align: left;">Some gammons</td>
<td style="text-align: right;">0.256</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: right;">-0.035</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Many gammons</td>
<td style="text-align: right;">0.256</td>
<td style="text-align: right;">0.335</td>
<td style="text-align: right;">-0.078</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<ul>
<li><p>If White does <em>not</em> have an automatic recube available (as in a last-roll situation), he should be careful about taking a redouble at this score.</p></li>
<li><p>Even if the auto-redouble is available, it’s considerable harder to find a take in a race than for money.</p></li>
<li><p>Of course, after redouble/take/auto-redouble, it is double match point, so gammons are harmless – this could lead to takes that normally ‘look like’ big passes.</p></li>
</ul>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-59-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No redouble:     +0,869 (-0,075)
 Redouble/Take:   +0,944
 Redouble/Pass:   +1,000 (+0,056)

5-away, 4-away, Cubeful Equities:
 No redouble:     +0,860 (-0,140)
 Redouble/Take:   +1,121 (+0,121)
 Redouble/Pass:   +1,000</code></pre>
</div>
</div>
</div>
<p>This is a 5-roll position with drawbacks: White can’t use 22 to save a roll and 11 is not fully effective. Those are quite expensive drawbacks, rather than 28% in in a pure 5-roll, white has only 24% here. Enought for a good money take, not enough at 5-away, 4-away, even taking into consideration the automatic recube.</p>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-60-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No redouble:     +0,880 (-0,120)
 Redouble/Take:   +1,096 (+0,096)
 Redouble/Pass:   +1,000

5-away, 4-away, Cubeful Equities:
 No redouble:     +0,874
 Redouble/Take:   +0,436 (-0,438)
 Redouble/Pass:   +1,000 (+0,126)</code></pre>
</div>
</div>
</div>
<p>This looks scary for money, and it is indeed a pass. But of course the many gammons don’t matter after double/take/re-double, so White has a super easy take and Black is better off not doubling.</p>
</section>
<section id="away-3-away-4" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="away-3-away-4">5-away, 3-away</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Estimated live cube take points at 5-away, 3-away, cube at 2</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Position type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, match</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, money</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Last roll</td>
<td style="text-align: right;">0.211</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">-0.039</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race</td>
<td style="text-align: right;">0.158</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">-0.056</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A little gammon</td>
<td style="text-align: right;">0.158</td>
<td style="text-align: right;">0.261</td>
<td style="text-align: right;">-0.103</td>
</tr>
<tr class="even">
<td style="text-align: left;">Some gammons</td>
<td style="text-align: right;">0.158</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: right;">-0.133</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Many gammons</td>
<td style="text-align: right;">0.158</td>
<td style="text-align: right;">0.335</td>
<td style="text-align: right;">-0.176</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<ul>
<li><p>A redouble here is of course for the match, so one needs only the same winning probability as when trailing 5-away, 1-away: 15.8%</p></li>
<li><p>Caveat is when you don’t get to redouble, as in a last-roll or virtually last roll situation. Then we need a good bit more – but still less than for money.</p></li>
</ul>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-62-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No redouble:     +0,702 (-0,298)
 Redouble/Take:   +1,231 (+0,231)
 Redouble/Pass:   +1,000

5-away, 3-away, Cubeful Equities:
 No redouble:     +0,688 (-0,182)
 Redouble/Take:   +0,870
 Redouble/Pass:   +1,000 (+0,130)</code></pre>
</div>
</div>
</div>
<p>White can find the 15.8% he needs to take here.</p>
</section>
</section>
<section id="the-rare-8-cube" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="the-rare-8-cube">The rare 8-cube</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Estimated live cube take points at 5-away, 5-away, cube at 4</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Position type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, match</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Take point, money</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Last roll</td>
<td style="text-align: right;">0.158</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">-0.092</td>
</tr>
<tr class="even">
<td style="text-align: left;">Race</td>
<td style="text-align: right;">0.158</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">-0.056</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A little gammon</td>
<td style="text-align: right;">0.158</td>
<td style="text-align: right;">0.261</td>
<td style="text-align: right;">-0.103</td>
</tr>
<tr class="even">
<td style="text-align: left;">Some gammons</td>
<td style="text-align: right;">0.158</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: right;">-0.133</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Many gammons</td>
<td style="text-align: right;">0.158</td>
<td style="text-align: right;">0.335</td>
<td style="text-align: right;">-0.176</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>The non-automatic 8-cube arises only at 5-away, 5-away, so like before we have at take point at 15.8%. If gammons are likely this could lead to the unusual too-good-to-double-take situation. When this happens, the doubler is worse off doubling <em>no matter</em> if the opponent passes or takes.</p>
<p>Could look like this:</p>
<div>

</div>
<div class="cell column-page-right quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="5-point-match_files/figure-html/unnamed-chunk-64-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<pre><code>



Money game, Cubeful Equities:
 No redouble:     +1,646
 Redouble/Take:   +3,054 (+1,409)
 Redouble/Pass:   +1,000 (-0,646)

5-away, 5-away, Cubeful Equities:
 No redouble:     +1,003
 Redouble/Take:   +0,981 (-0,022)
 Redouble/Pass:   +1,000 (-0,003)
 
1296 Games rolled with Variance Reduction.
Moves: 3-ply, cube decisions: XG Roller</code></pre>
</div>
</div>
</div>
<p>Black is crazy too-good for money, but both too-good and not good enough at 5-away, 5-away holding a 4-cube.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/lassehjorthmadsen\.github\.io\/bganalyses\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>