---
title: "Confidence intervals for PR"
author: "Lasse Hjorth Madsen"
date: today 
format: 
  html:
    fig-width: 4
    fig-height: 4
toc: true
toc-expand: true
toc-depth: 3
editor: source
execute:
  echo: false
  warning: false
  cache: true
---

```{r setup}
#| cache: false
library(tidyverse)
library(kableExtra)
library(ggrepel)

devtools::load_all(path = "../../bglab")
```

## Why this?

Performance Rating, PR, is the defacto standard for measuring playing strength in backgammon. It's the average error per decision (i.e. non-forced and non-trivial play). But for an individual player PR varies a lot from match to match, from tournament to tournament, or, presumably, over time. This is expected, since players face very different sets of decisions in each match. A match is, in essence, a random sample of all possible decision one will have to make in backgammon.

It would be nice to calculate confidence intervals and compute p-values, to give an idea of how accurate a given PR-result is.

For example:

- Suppose I estimate my own playing strength at around, say, 4.0 PR. Now suppose I play a 17-point match at 6.0 PR. What is the most reasonable interpretation: a) That I for some reason played worse than usual, or b) That this is just an example of the natural variation given the relative small sample size?

- Or, suppose that I play 8 matches in some tournament, for a combined PR of 4.5. Then, a year a later, I play 5.5 in another tournament. Is this evidence that my play has gotten worse, or is it likely to be just statistical noise?

The last case was a real life experience for me at the qualification tournaments for the Danish national team in 2024 and 2025. It would be nice to more confidently interpret these data.



## To-do

- Update bgmoves dataset
- In bgmoves define a decision
- Use bgmoves dataset to estimate variance
- Split the variance between me/opponents, and checker play, cube decisions.
- Calculate average number of moves for various match lengths
- Calculate example of confidence intervals.
- Test hypotheses:
    - PR_2025 < PR_2024
    - PR_live < PR_online
- Examine data from VM kval. 2024 and 2025
  - Distribution of PRs
  - Do players PR vary by about the expected amount?